// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCzpDOzX6mLaEwfX7at2M9XC53w2y-qXM',
    appId: '1:341575638360:web:ca8d88938112545f42592d',
    messagingSenderId: '341575638360',
    projectId: 'personifyu-5f48c',
    authDomain: 'personifyu-5f48c.firebaseapp.com',
    storageBucket: 'personifyu-5f48c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbetsPQOybxxDBz1P0uNWEe9qjncTZyiw',
    appId: '1:341575638360:android:3c54df0531d9b3a342592d',
    messagingSenderId: '341575638360',
    projectId: 'personifyu-5f48c',
    storageBucket: 'personifyu-5f48c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz-qRMJa2mPbp2QsqIb4cGrhS3OqKLOV0',
    appId: '1:341575638360:ios:2840a8c65fafd0e042592d',
    messagingSenderId: '341575638360',
    projectId: 'personifyu-5f48c',
    storageBucket: 'personifyu-5f48c.appspot.com',
    iosBundleId: 'com.example.personifyu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz-qRMJa2mPbp2QsqIb4cGrhS3OqKLOV0',
    appId: '1:341575638360:ios:2840a8c65fafd0e042592d',
    messagingSenderId: '341575638360',
    projectId: 'personifyu-5f48c',
    storageBucket: 'personifyu-5f48c.appspot.com',
    iosBundleId: 'com.example.personifyu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCzpDOzX6mLaEwfX7at2M9XC53w2y-qXM',
    appId: '1:341575638360:web:bd9bc5e3a70acce042592d',
    messagingSenderId: '341575638360',
    projectId: 'personifyu-5f48c',
    authDomain: 'personifyu-5f48c.firebaseapp.com',
    storageBucket: 'personifyu-5f48c.appspot.com',
  );

}